name: redux_thunk_boilerplate
description: Flutter redux thunk boilerplate
version: 0.1.0

environment:
  flutter: 1.9.1+hotfix.2

dependencies:
  flutter:
    sdk: flutter

  # Redux
  redux: 3.0.0
  flutter_redux: 0.5.3
  redux_logging: 0.3.0
  redux_thunk: 0.2.1
  redux_persist_flutter: 0.8.2
  redux_persist: 0.8.2

  # Layout & design
  flutter_staggered_grid_view: 0.3.0
  loading_overlay: 0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.7.1
  json_serializable: 3.2.2
  json_annotation: 3.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  assets:
  - lib/src/assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
